server:
  port: 8011

spring:
  application:
    name: service1 #스프링 컨피그의 디렉토리명 과 일치해야 함
  profiles:
    active:
      default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://ec2-13-125-49-175.ap-northeast-2.compute.amazonaws.com:8761/eureka/
    registry-fetch-interval-seconds: 5
    disable-delta: true

management:
  endpoints:
    web:
      exposure:
        include: "*"